[theme]
base = "light"
primaryColor = "#315ce3"
backgroundColor = "#f5f7fb"
secondaryBackgroundColor = "#ffffff"
textColor = "#182a43"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
maxUploadSize = 30
